app:
  auth:
    tokenSecret: secret
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: https://hdkwebshopping.vercel.app,https://hdkwebshopping.azurewebsites.net,http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
#     - http://localhost:3000/oauth2/redirect
#     - https://hdkwebshopping.azurewebsites.net/oauth2/redirect
      - https://hdkwebshopping.vercel.app
server:
  port: 8080
#spring:
#  datasource:
#    password: 123456
#    url: jdbc:mysql://localhost:3306/hdkweb
#    username: root
spring:
  datasource:
    password: hdkweb@827
    url: jdbc:mysql://hdkweb.mysql.database.azure.com:3306/hdkweb?useSSL=true
    username: myadmin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: kfwcsyymsqnrrvdn
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: leafnote2022@gmail.com
  security:
      oauth2:
        client:
          registration:
            google:
              clientId: 793406760016-6a0k4g8d4ti37plqieqk4q4ochdog6er.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
